###
# Author : pepper (Shane Culpepper)
# Date   : Sat 16 Jul 2011
#
# A general makefile that will automatically make any project where all of the
# source and header files are in one directory.
#
# If there are extra source or header files in the directory that are not part
# of the project they should be moved or renamed, or else the SRC and HDR
# variables should be set manually otherwise compilation may fail.
#
# For more information about makefiles, check here:
#     http://www.gnu.org/software/make/manual/make.html
###

# The name of the applications we're trying to generate
TARGET = pathview pathtime

SRC = libutil.c liblist.c libstack.c libpqueue.c libgraph.c libbits.c libpath.c
HDR = libutil.h liblist.h libbits.h libgraph.h libstack.h libpqueue.h libpath.h

# The following three lines can be used to automatically generate the SRC, HDR
# and OBJ variables instead of doing it statically as above
OBJ := $(SRC:.c=.o)

# These variables are used by make in all of it's automatic rules.
# Specifically, use CFLAGS for the "-g -O0" option if you want to do debugging,
# and LDFLAGS for the "-lm" option if you are using the math library.
CC = gcc
#CFLAGS = -W -Wall -ansi -O3 -D_XOPEN_SOURCE=500
CFLAGS = -W -Wall -ansi -std=c99 -g -O0 -D_XOPEN_SOURCE=500
LDFLAGS = -lm -lcurses

all : test_pqueue test_dmetric pathview pathtime gen_maze

test_darray:
	$(CC) $(CFLAGS) -o $@ libutil.c libdarray.c test_darray.c

test_pqueue:
	$(CC) $(LDFLAGS) -o $@ libutil.c liblist.c libpqueue.c test_pqueue.c 

test_path: $(OBJ)
	$(CC) $(CFLAGS) -o $@ $(OBJ) test_path.c $(LDFLAGS)

test_dmetric: $(OBJ)
	$(CC) $(LDFLAGS) -o $@ $(OBJ) test_dmetric.c 

pathtime: $(OBJ)
	$(CC) -o $@ $(OBJ) pathtime.c $(LDFLAGS)

pathview: $(OBJ)
	$(CC) -o $@ $(OBJ) pathview.c $(LDFLAGS)

gen_maze:
	$(CC) -o $@ libutil.c liblist.c libgraph.c libbits.c gen_maze.c $(LDFLAGS) 

# This generates the dependencies between your various .c and .h files, using
# the c compiler's -MM option.
depend : $(SRC) $(HDR)
	$(CC) $(CFLAGS) -MM $(SRC) > depend

# This includes the dependencies made with the previous rule, and in fact forces
# them to be generated.
-include depend

# The rules below clean up any files generated by the make process.  clean
# should be run to clear out the temporary files, and clobber should be run if
# you modify your makefile (for example to change the CFLAGS or LDFLAGS options)
# so that you can get a clean recompile.
.PHONY : test clean

clean :
	-rm -f depend
	-rm -f $(TARGET) gen_maze $(OBJ) test_dmetric test_pqueue test_darray
	-rm -f *~ 
